name: golang/test
on: pull_request
jobs:
  testrace:
    name: testrace
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.16'
      - uses: actions/setup-go@v2
      - run: yarn
      - run: yarn setup:contracts
      - run: go run ./core local db preparetest
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/chainlink_test?sslmode=disable'
      - run: go test -timeout 1800s -p 2 -race ./core/... -parallel 2
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/chainlink_test?sslmode=disable'
